# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
fastlane_require "dotenv"

before_all do
  Dotenv.load ".env.secret"
end 

desc "create on Developer protal and App store connect"
lane :create_app do
  create_app_online #produce
end

platform :ios do
  #before_all do
  # Dotenv.load ".env.ios"
  #end

  desc "Sync signing"
  lane :signing do
    sync_code_signing #match
    mapping = Actions.lane_context[
      SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING
      ]
    update_code_signing_settings(
      profile_name: mapping[ENV['APP_IDENTIFIER']]
              )
  end

  desc "Install pod dependencies"
    lane :install_pods do          
         cocoapods(
	       use_bundle_exec:false,
         repo_update: true,
         allow_root:true
    	  ) 
 
    end

  desc "Build binary"
  lane :build do
    install_pods
    signing
    increment_build
    build_ios_app #gym
  end

  desc "Incrementing Build Number"
  lane :increment_build do
            current_build_number = latest_testflight_build_number(version:ENV['APP_VERSION'])
            increment_build_number(
            xcodeproj: 'ios/reactRaj.xcodeproj',
            build_number: current_build_number + 1
           ) 
  end

  desc "Release"
  lane :release do
    #build
    app_store_connect_api_key(
      key_id: "Q9HTB2P26H",
      issuer_id: "1b91167b-27d1-41b3-9ee6-d1f5c3f0f3ff",
      key_content: "-----BEGIN PRIVATE KEY-----\nMIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgmqk0KSvZ3M4tHxXU\ngFxf5XASK7H6sUElb1Oi1cOWPAagCgYIKoZIzj0DAQehRANCAAQhimqQ6hzG1TJH\nKAaLQ0Zt/OPjgOOgWNxmhc2i5J7s7u4mv5yB4j/QOwsUN0+9YMHRzshdwjlE1are\nBXu7Bose\n-----END PRIVATE KEY-----",
      duration: 1200,
      in_house: false
    )   
    install_pods
    signing
    increment_build
    build_ios_app #gym
    upload_to_testflight
    #  pilot(
    #    ipa: "ios/build/reactRaj.ipa",
    #    skip_submission: true,
    #    skip_waiting_for_build_processing: true
    #  )
  end
end
