# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

#default_platform(:ios)
fastlane_require "dotenv"

before_all do
  Dotenv.load ".env.secret"
end 

desc "create on Developer protal and App store connect"
lane :create_app do
  create_app_online #produce
end

platform :ios do
  #before_all do
  # Dotenv.load ".env.ios"
  #end

  desc "Sync signing"
  lane :signing do
    sync_code_signing #match
    mapping = Actions.lane_context[
      SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING
      ]
    update_code_signing_settings(
      profile_name: mapping[ENV['APP_IDENTIFIER']]
              )
  end

  desc "Build binary"
  lane :build do
    signing
    increment_build
    build_ios_app #gym
  end

  desc "Incrementing Build Number"
  lane :increment_build do
            current_build_number = latest_testflight_build_number(version:ENV['APP_VERSION'])
            increment_build_number(
            build_number: current_build_number + 1
           ) 
  end

  desc "Release"
  lane :release do
    build
    #upload_to_testflight
    increment_build
     pilot(
       ipa: "build/ios/reactRaj.ipa",
       skip_submission: true,
       skip_waiting_for_build_processing: true
     )
  end
end
